name: "Test typescript-action"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  operating-systems:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: jaxxstorm/connecti
          arch: amd64
          cache: enable